#!/usr/bin/env python
# -*- mode: Python; -*-

import click
import requests

class config:
    SERVER='http://localhost:8080'

    @classmethod
    def path(cls, path):
        return cls.SERVER + path

@click.group(invoke_without_command=True)
@click.option('--server', default=config.SERVER)
@click.pass_context
def lager(ctx, server):
    config.SERVER=server
    if ctx.invoked_subcommand is None:
        ctx.invoke(status)

@lager.command()
def status():
    r = requests.get(config.path('/'))
    print(r.text)

@lager.command()
@click.argument('cursor')
def step(cursor):
    r = requests.get(config.path('/step'),
                     params={'cursor': cursor})
    print(r.text)

@lager.command()
@click.argument('cursor')
def goto(cursor):
    r = requests.post(config.path('/goto'),
                      params={'cursor': cursor})
    print(r.text)

@lager.command()
def undo():
    r = requests.post(config.path('/undo'))
    print(r.text)

@lager.command()
def redo():
    r = requests.post(config.path('/redo'))
    print(r.text)

if __name__ == '__main__':
    lager()
